use_frameworks!
target 'PovioKit_Tests' do
  pod 'PovioKit', :path => '../'
  pod 'FBSDKCoreKit', '4.38.0'
  pod 'FBSDKLoginKit', '4.38.0'
  pod 'FBSDKShareKit', '4.38.0'
  pod 'TwitterKit', '3.4.0'
end
