osx_image: xcode10.2
language: swift
xcode_workspace: Example/PovioKit.xcworkspace
xcode_scheme: Pods-PovioKit_Tests
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone Xs
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
#script:
#- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/PovioKit.xcworkspace -scheme PovioKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
#- pod lib lint
