name: CI

on: 
  push:
  pull_request:
    types: [opened]

jobs:
  Tests:
    runs-on: macos-latest
    steps:
    - name: Cancel previous jobs
      uses: styfle/cancel-workflow-action@0.9.1
    - name: Checkout
      uses: actions/checkout@v2
#    - name: Lint
#      run: swiftlint
    - name: Generate xcodeproj
      run: swift package generate-xcodeproj
    - name: Run tests
      run: xcodebuild test -destination 'name=iPhone 12' -scheme 'PovioKit-Package'
