name: SPM Outdated

on: 
  schedule:
    - cron: '0 0 * * 7' # run every Sunday midnight

jobs:
  swiftpm:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: MeilCli/swiftpm-update-check-action@v3
      id: outdated
